version: '3'

services:
  # Web service layer
  uehook_nginx:
    image: nginx:1.13
    container_name: uehook_nginx
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./docker/services/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    depends_on:
      - uehook_app
    networks:
      - uehook_network

  uehook_mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: uehook_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - uehook_network
    depends_on:
      - uehook_app

  uehook_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    container_name: uehook_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: "remote_host=${DOCKER_XDEBUG_PORT} remote_connect_back=0 remote_enable=1 idekey=PHPSTORM remote_port=9001 remote_autostart=1"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - uehook_network

  # Data persistence service layer
  uehook_mysql:
    image: mysql:5.7.22
    env_file:
      - .env
    container_name: uehook_db
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - uehook_data:/var/lib/mysql
    networks:
      - uehook_network

  uehook_redis:
    container_name: uehook_redis
    image: redis:latest
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - uehook_network
    volumes:
      - redis_data:/data

networks:
  uehook_network:
    driver: bridge

volumes:
  uehook_data:
    driver: local

  redis_data:
